version: "3.8"

services:
  web:
    build: .
    container_name: simple_web_app
    ports:
      - "5000:5000"
    environment:
      - CUSTOM_MESSAGE=Hello from Docker Compose environment variable!
